#!/bin/bash
WEB_DIR=/var/www/html
echo "<HTML>
<HEAD>
<style>
.title{front-size: 1em; color: white; background:#0863CE; padding: 0.1em 0.2em;}
table
{
	border-collapse:collapse;
}
table, td, th
{
	border:1px solid black;
}
</style>
<meta http-equiv='Content-Type'	content='text/html; charset=UTF-8'/>
</HEAD>
<BODY>" > $WEB_DIR/report.html

#view hostname and insert it at the top of the html body
HOST=$(hostname)
echo "Filesystem usage for host <strong>$HOST</strong><br>
Last updated: <strong>$(date)</strong><br><br>
<table border='1'>
<tr><th class='title'>Filesystem</td>
<th class='title'>Size</td>
<th class='title'>Use %</td>
</tr>" >> $WEB_DIR/report.html
#read the output of df -h line by line
while read line; do
echo "<tr><td align='center'>" >> $WEB_DIR/report.html
echo $line | awk '{print $1}' >> $WEB_DIR/report.html
echo "</td><td align='center'>" >> $WEB_DIR/report.html
echo $line | awk '{print $2}' >> $WEB_DIR/report.html
echo "</td><td align='center'>" >> $WEB_DIR/report.html
echo $line | awk '{print $5}' >> $WEB_DIR/report.html
echo "</td></tr>" >> $WEB_DIR/report.html
done < <(df -h |grep -vi filesystem)
echo "</table></BODY></HTML>" >> $WEB_DIR/report.html
